const owlGrasshopper: Array<string> = [
  'The Owl always takes her sleep during the day.',
  'Then after sundown, when the rosy light fades from the sky and the shadows rise slowly through the wood, out she comes ruffling and blinking from the old hollow tree.',
  'Now her weird "hoo-hoo-hoo-oo-oo" echoes through the quiet wood, and she begins her hunt for the bugs and beetles, frogs and mice she likes so well to eat.',
  'Now there was a certain old Owl who had become very cross and hard to please as she grew older, especially if anything disturbed her daily slumbers.',
  'One warm summer afternoon as she dozed away in her den in the old oak tree, a Grasshopper nearby began a joyous but very raspy song.',
  "Out popped the old Owl's head from the opening in the tree that served her both for door and for window.",
  '"Get away from here, sir," she said to the Grasshopper.',
  '"Have you no manners? You should at least respect my age and leave me to sleep in quiet!"',
  'But the Grasshopper answered saucily that he had as much right to his place in the sun as the Owl had to her place in the old oak.',
  'Then he struck up a louder and still more rasping tune.',
  'The wise old Owl knew quite well that it would do no good to argue with the Grasshopper, nor with anybody else for that matter.',
  'Besides, her eyes were not sharp enough by day to permit her to punish the Grasshopper as he deserved.',
  'So she laid aside all hard words and spoke very kindly to him.',
  '"Well sir," she said, "if I must stay awake, I am going to settle right down to enjoy your singing.',
  'Now that I think of it, I have a wonderful wine here, sent me from Olympus, of which I am told Apollo drinks before he sings to the high gods.',
  'Please come up and taste this delicious drink with me.',
  'I know it will make you sing like Apollo himself."',
  "The foolish Grasshopper was taken in by the Owl's flattering words.",
  "Up he jumped to the Owl's den, but as soon as he was near enough so the old Owl could see him clearly, she pounced upon him and ate him up.",
  'This story is meant to communicate the following moral.',
  'Flattery is not a proof of true admiration.',
  'Do not let flattery throw you off your guard against an enemy.'
]
const gnatBull: Array<string> = [
  'A Gnat flew over the meadow with much buzzing for so small a creature and settled on the tip of one of the horns of a Bull.',
  'After he had rested a short time, he made ready to fly away.',
  "But before he left he begged the Bull's pardon for having used his horn for a resting place.",
  '"You must be very glad to have me go now," he said.',
  '"It\'s all the same to me," replied the Bull.',
  '"I did not even know you were there."',
  'This story is meant to communicate the following moral.',
  'We are often of greater importance in our own eyes than in the eyes of our neighbor.',
  'The smaller the mind the greater the conceit.'
]
const lionMouse: Array<string> = [
  'A Lion lay asleep in the forest, his great head resting on his paws.',
  "A timid little Mouse came upon him unexpectedly, and in her fright and haste to get away, ran across the Lion's nose.",
  'Roused from his nap, the Lion laid his huge paw angrily on the tiny creature to kill her.',
  '"Spare me!" begged the poor Mouse.',
  '"Please let me go and some day I will surely repay you."',
  'The Lion was much amused to think that a Mouse could ever help him.',
  'But he was generous and finally let the Mouse go.',
  "Some days later, while stalking his prey in the forest, the Lion was caught in the toils of a hunter's net.",
  'Unable to free himself, he filled the forest with his angry roaring.',
  'The Mouse knew the voice and quickly found the Lion struggling in the net.',
  'Running to one of the great ropes that bound him, she gnawed it until it parted, and soon the Lion was free.',
  '"You laughed when I said I would repay you," said the Mouse.',
  '"Now you see that even a Mouse can help a Lion."',
  'The moral of the story is, "A kindness is never wasted".'
]
const wolfCrane: Array<string> = [
  'A Wolf had been feasting too greedily, and a bone had stuck crosswise in his throat.',
  'He could get it neither up nor down, and of course he could not eat a thing.',
  'Naturally that was an awful state of affairs for a greedy Wolf.',
  'So away he hurried to the Crane.',
  'He was sure that she, with her long neck and bill, would easily be able to reach the bone and pull it out.',
  '"I will reward you very handsomely," said the Wolf, "if you pull that bone out for me."',
  "The Crane, as you can imagine, was very uneasy about putting her head in a Wolf's throat.",
  'But she was grasping in nature, so she did what the Wolf asked her to do.',
  'When the Wolf felt that the bone was gone, he started to walk away.',
  '"But what about my reward!" called the Crane anxiously.',
  '"What!" snarled the Wolf, whirling around.',
  '"Haven\'t you got it?',
  'Isn\'t it enough that I let you take your head out of my mouth without snapping it off?"',
  'The moral of the story is, "Expect no reward for serving the wicked".'
]
const foxGrapes: Array<string> = [
  'A Fox one day spied a beautiful bunch of ripe grapes hanging from a vine trained along the branches of a tree.',
  'The grapes seemed ready to burst with juice, and the Fox\'s mouth watered as he gazed longingly at them.',
  'The bunch hung from a high branch, and the Fox had to jump for it.',
  'The first time he jumped he missed it by a long way.',
  'So he walked off a short distance and took a running leap at it, only to fall short once more.',
  'Again and again he tried, but in vain.',
  'Now he sat down and looked at the grapes in disgust.',
  '"What a fool I am," he said. "Here I am wearing myself out to get a bunch of sour grapes that are not worth gaping for."',
  'And off he walked very, very scornfully.',
  'The moral of the story is, "There are many who pretend to despise and belittle that which is beyond their reach".'
]
const townMouse: Array<string> = [
  'A Town Mouse once visited a relative who lived in the country.',
  'For lunch the Country Mouse served wheat stalks, roots, and acorns, with a dash of cold water for drink.',
  'The Town Mouse ate very sparingly, nibbling a little of this and a little of that, and by her manner making it very plain that she ate the simple food only to be polite.',
  'After the meal the friends had a long talk, or rather the Town Mouse talked about her life in the city while the Country Mouse listened.',
  'They then went to bed in a cozy nest in the hedgerow and slept in quiet and comfort until morning.',
  'In her sleep the Country Mouse dreamed she was a Town Mouse with all the luxuries and delights of city life that her friend had described for her.',
  'So the next day when the Town Mouse asked the Country Mouse to go home with her to the city, she gladly said yes.',
  'When they reached the mansion in which the Town Mouse lived, they found on the table in the dining room the leavings of a very fine banquet.',
  'There were sweetmeats and jellies, pastries, delicious cheeses, indeed, the most tempting foods that a Mouse can imagine.',
  'But just as the Country Mouse was about to nibble a dainty bit of pastry, she heard a Cat mew loudly and scratch at the door.',
  'In great fear the Mice scurried to a hiding place, where they lay quite still for a long time, hardly daring to breathe.',
  'When at last they ventured back to the feast, the door opened suddenly and in came the servants to clear the table, followed by the House Dog.',
  'The Country Mouse stopped in the Town Mouse\'s den only long enough to pick up her carpet bag and umbrella.',
  '"You may have luxuries and dainties that I have not," she said as she hurried away, "but I prefer my plain food and simple life in the country with the peace and security that go with it."',
  'The moral of the story is, "Poverty with security is better than plenty in the midst of fear and uncertainty."'
]
const bellingCat: Array<string> = [
  'The Mice once called a meeting to decide on a plan to free themselves of their enemy, the Cat.',
  'At least they wished to find some way of knowing when she was coming, so they might have time to run away.',
  'Indeed, something had to be done, for they lived in such constant fear of her claws that they hardly dared stir from their dens by night or day.',
  'Many plans were discussed, but none of them was thought good enough.',
  'At last a very young Mouse got up and said:',
  '"I have a plan that seems very simple, but I know it will be successful. All we have to do is to hang a bell about the Cat\'s neck. When we hear the bell ringing we will know immediately that our enemy is coming."',
  'All the Mice were much surprised that they had not thought of such a plan before.',
  'But in the midst of the rejoicing over their good fortune, an old Mouse arose and said:',
  '"I will say that the plan of the young Mouse is very good. But let me ask one question: Who will bell the Cat?"',
  'The moral of the story is "It is one thing to say that something should be done, but quite a different matter to do it."'
]
const frogOx: Array<string> = [
  'An Ox came down to a reedy pool to drink.',
  'As he splashed heavily into the water, he crushed a young Frog into the mud.',
  'The old Frog soon missed the little one and asked his brothers and sisters what had become of him.',
  '"A great big monster," said one of them, "stepped on little brother with one of his huge feet!"',
  '"Big, was he!" said the old Frog, puffing herself up. "Was he as big as this?"',
  '"Oh, much bigger!" they cried.',
  'The Frog puffed up still more.',
  '"He could not have been bigger than this," she said.',
  'But the little Frogs all declared that the monster was much, much bigger and the old Frog kept puffing herself out more and more until, all at once, she burst.',
  'The moral of the story is, "Do not attempt the impossible.".'
]
const threeLittlePigs: Array<string> = [
  'Once upon a time there was an old mother pig who had three little pigs and not enough food to feed them.',
  'So when they were old enough, she sent them out into the world to seek their fortunes.',
  'The first little pig was very lazy.',
  'He didn\'t want to work at all and he built his house out of straw.',
  'The second little pig worked a little bit harder but he was somewhat lazy too and he built his house out of sticks.',
  'Then, they sang and danced and played together the rest of the day.',
  'The third little pig worked hard all day and built his house with bricks.',
  'It was a sturdy house complete with a fine fireplace and chimney.',
  'It looked like it could withstand the strongest winds.',
  'The next day, a wolf happened to pass by the lane where the three little pigs lived; and he saw the straw house, and he smelled the pig inside.',
  'He thought the pig would make a mighty fine meal and his mouth began to water.',
  'So he knocked on the door and said:',
  '"Little pig! Little pig! Let me in! Let me in!"',
  'But the little pig saw the wolf\'s big paws through the keyhole, so he answered back:',
  '"No! No! No! Not by the hairs on my chinny chin chin!"',
  'Then the wolf showed his teeth and said:',
  '"Then I\'ll huff and I\'ll puff and I\'ll blow your house down."',
  'So he huffed and he puffed and he blew the house down!',
  'The wolf opened his jaws very wide and bit down as hard as he could, but the first little pig escaped and ran away to hide with the second little pig.',
  'The wolf continued down the lane and he passed by the second house made of sticks; and he saw the house, and he smelled the pigs inside, and his mouth began to water as he thought about the fine dinner they would make.',
  'So he knocked on the door and said:',
  '"Little pigs! Little pigs! Let me in! Let me in!"',
  'But the little pigs saw the wolf\'s pointy ears through the keyhole, so they answered back:',
  '"No! No! No! Not by the hairs on our chinny chin chin!"',
  'So the wolf showed his teeth and said:',
  '"Then I\'ll huff and I\'ll puff and I\'ll blow your house down!"',
  'So he huffed and he puffed and he blew the house down!',
  'The wolf was greedy and he tried to catch both pigs at once, but he was too greedy and got neither!',
  'His big jaws clamped down on nothing but air and the two little pigs scrambled away as fast as their little hooves would carry them.',
  'The wolf chased them down the lane and he almost caught them.',
  'But they made it to the brick house and slammed the door closed before the wolf could catch them.',
  'The three little pigs they were very frightened, they knew the wolf wanted to eat them.',
  'And that was very, very true.',
  'The wolf hadn\'t eaten all day and he had worked up a large appetite chasing the pigs around and now he could smell all three of them inside and he knew that the three little pigs would make a lovely feast.',
  'So the wolf knocked on the door and said:',
  '"Little pigs! Little pigs! Let me in! Let me in!"',
  'But the little pigs saw the wolf\'s narrow eyes through the keyhole, so they answered back:',
  '"No! No! No! Not by the hairs on our chinny chin chin!"',
  'So the wolf showed his teeth and said:',
  '"Then I\'ll huff and I\'ll puff and I\'ll blow your house down."',
  'Well! he huffed and he puffed.',
  'He puffed and he huffed.',
  'And he huffed, huffed, and he puffed, puffed; but he could not blow the house down.',
  'At last, he was so out of breath that he couldn\'t huff and he couldn\'t puff anymore.',
  'So he stopped to rest and thought a bit.',
  'But this was too much.',
  'The wolf danced about with rage and swore he would come down the chimney and eat up the little pig for his supper.',
  'But while he was climbing on to the roof the little pig made up a blazing fire and put on a big pot full of water to boil.',
  'Then, just as the wolf was coming down the chimney, the little piggy pulled off the lid, and plop! in fell the wolf into the scalding water.',
  'So the little piggy put on the cover again, boiled the wolf up, and the three little pigs ate him for supper.'
]
interface Story {
  title: string;
  story: Array<string>;
}
const stories: Array<Story> = [
  { title: '🐷🐷 The Three Little Pigs', story: threeLittlePigs },
  { title: '🐸🐂 The Frog and the Ox', story: frogOx },
  { title: '🔔🐈 Belling the Cat', story: bellingCat },
  { title: '🐁🐀 The Town Mouse & the Country Mouse', story: townMouse },
  { title: '🦊🍇 The Fox & the Grapes', story: foxGrapes },
  { title: '🐺🦢 The Wolf & the Crane', story: wolfCrane },
  { title: '🦁🐁 The Lion & the Mouse', story: lionMouse },
  { title: '🪰🐂 The Gnat & the Bull', story: gnatBull },
  { title: '🦉🦗 The Owl & the Grasshopper', story: owlGrasshopper }
]
export { stories }
